blog/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('pages.index');
})->name('index');

Route::get('/contact', function () {
    return view('pages.contact');
})->name('contact');

Route::get('/changeLang/{local}', "cookiesController@setCookie")->name('changeLang');


Route::get('/catalogue', function () {
    return view('pages.catalog');
})->name('catalog');

// Route::get('/article', function () {
//     return view('pages.article');
// })->name('article');

Route::resource('article', 'ArticleController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

blog/app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    protected $fillable = [
        'titre',
        'body',
        'img_url',
        'user_id',
    ];

    public function auteur()
    {
        return $this->belongsTo('App\User', 'user_id');
    }
}

blog/app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

blog/app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Article;
use Illuminate\Http\Request;
use Auth;
use Illuminate\Http\Response;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $response = new Response('Hello World');
        // $response->withCookie(cookie('local', 'ar', 525600));
        // return $response;

        $articles = Article::orderBy('created_at', "desc")->paginate(12);
        return view('pages.article.index', ['articles' => $articles]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user = Auth::user();
        if ($user) {
            return view('pages.article.create');
        } else {
            return redirect('/login');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'titre' => 'required|max:255',
            'body' => 'required',
            'img_url' => "url|nullable",
        ]);

        $article = Article::create([
            'titre' => $request->titre,
            'body' => $request->body,
            'img_url' => $request->img_url,
            'user_id' => Auth::user()->id,
        ]);

        return redirect(route("article.show", $article->id));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function show(Article $article)
    {
        $article->parsed_body = explode("\n", $article->body);
        return view('pages.article.show', ['article' => $article]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function edit(Article $article)
    {
        // return $article;
        $user = Auth::user();
        if ($user) {
            if ($user->id == $article->user_id) {
                return view('pages.article.edit', ['article' => $article]);
            } else {
                return redirect(route('article.index'));
            }
        } else {
            return redirect('/login');
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Article $article)
    {
        $user = Auth::user();
        if ($user) {
            if ($user->id == $article->user_id) {
                $request->validate([
                    'titre' => 'required|max:255',
                    'body' => 'required',
                    'img_url' => "url|nullable",
                ]);

                $article->titre = $request->titre;
                $article->body = $request->body;
                $article->img_url = $request->img_url;
                $article->save();

                return redirect(route('article.show', $article->id));
            } else {
                return redirect(route('article.index'));
            }
        } else {
            return redirect('/login');
        }

        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function destroy(Article $article)
    {
        $user = Auth::user();
        if ($user) {
            if ($user->id == $article->user_id) {
                $article->delete();
            }
            return redirect(route('article.index'));
        } else {
            return redirect('/login');
        }
        return 'DELETING ' . $article->id;
    }
}

blog/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

blog/app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

blog/app/Http/Controllers/cookiesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Auth;

class cookiesController extends Controller
{
    public function setCookie(Request $request, $local)
    {
        if (Auth::user()) {
            Auth::user()->local =  $local;
            Auth::user()->save();
        }


        $minutes = 60*24*365;

        return back()->withCookie(cookie('local', $local, $minutes));
    }
}

blog/resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

blog/resources/views/includes/footer.blade.php
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <a href="#">Back to top</a>
    </p>
    <p>Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
    <p>New to Bootstrap? <a href="https://getbootstrap.com/">Visit the homepage</a> or read our <a href="/docs/4.4/getting-started/introduction/">getting started guide</a>.</p>
  </div>
</footer>

blog/resources/views/includes/header.blade.php
<?php
    $locals = ['ar', 'fr', 'en'];
?>

<nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <div class="container">

  <a class="navbar-brand" href="{{ route('index') }}">@lang("pages.home")</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{{ route('article.index') }}">@lang("pages.catalog") <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{{ route('contact') }}">@lang("pages.contact") <span class="sr-only">(current)</span></a>
      </li>
    </ul>

    <ul class="navbar-nav ">
        @foreach($locals as $l)
        <li class="nav-item ">
            <a class="nav-link" href="{{ route('changeLang', $l) }}">{{$l}}</a>
        </li>
        @endforeach

        @if(Auth::user())
        <li class="nav-item active">
            <span class="nav-link">@lang('pages.hello') {{Auth::user()->name}}</span>
            <li class="nav-item">
                <a class="nav-link" href="{{ route('logout') }}"
                   onclick="event.preventDefault();
                                 document.getElementById('logout-form').submit();">
                    {{ __('Logout') }}
                </a>
            </li>

            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                @csrf
            </form>
        </li>
        @else
        <a class="nav-link" href="{{ route('login') }}">@lang('pages.login')</a>
        <a class="nav-link" href="{{ route('register') }}">@lang('pages.register')</a>

        @endif


    </ul>
  </div>
  </div>
</nav>

blog/resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

blog/resources/views/layouts/public.blade.php
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Album example · Bootstrap</title>
    <link href="https://getbootstrap.com/docs/4.4/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://getbootstrap.com/docs/4.4/examples/album/album.css" rel="stylesheet">
    <link rel="stylesheet" href="{{asset('css/custom.css')}}">
  </head>
  <body>
    @include('includes.header')
    <main role="main">
      @yield('content')
    </main>
    @include('includes.footer')
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    @yield('js')

  </body>
</html>

blog/resources/views/pages/article/create.blade.php
@extends('layouts.public')
@section('content')
<div class="album py-5 bg-light">
  <div class="container">
      <h1>Ajouter un article</h1>
      <form action="{{route('article.store')}}" method="POST">
          @csrf
        <div class="form-group">
          <label for="exampleInputEmail1">Titre</label>
          <input
            type="text"
            class="form-control"
            id="titre"
            value="{{old('titre')}}"
            name="titre"
            >
        </div>
        @error('titre')
            <div class="alert alert-danger">{{ $message }}</div>
        @enderror
        <div class="form-group">
          <label for="exampleInputPassword1">Lien image de couverture</label>
          <input
            type="text"
            class="form-control"
            value="{{old('img_url')}}"
            id="img_url"
            name="img_url"
            >
            @error('img_url')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="form-group">
            <textarea
                class="form-control"
                id="body"
                name="body"
                rows="5"
            >{{old('body')}}</textarea>
            @error('body')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <button type="submit" class="btn btn-primary">Ajouter</button>
      </form>
  </div>
</div>


@endsection

blog/resources/views/pages/article/edit.blade.php
@extends('layouts.public')
@section('content')
<div class="album py-5 bg-light">
  <div class="container">
      <h1>Modifier un article</h1>
      <form action="{{route('article.update', $article->id)}}" method="POST">
          @method('PATCH')
          @csrf
        <div class="form-group">
          <label for="exampleInputEmail1">Titre</label>
          <input type="text" class="form-control" id="titre" name="titre"
            value="{{$article->titre}}">
        </div>
        @error('titre')
            <div class="alert alert-danger">{{ $message }}</div>
        @enderror
        <div class="form-group">
          <label for="exampleInputPassword1">Lien image de couverture</label>
          <input type="text" class="form-control" id="img_url" name="img_url"
            value="{{$article->img_url}}" >
            @error('img_url')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="form-group">
            <textarea
                class="form-control"
                id="body"
                name="body"
                rows="5"
            >{{$article->body}}</textarea>
            @error('body')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <button type="submit" class="btn btn-primary">Modifier</button>
      </form>
  </div>
</div>


@endsection

blog/resources/views/pages/article/index.blade.php
@extends('layouts.public')
@section('content')
<div class="album py-5 bg-light">
  <div class="container">
      @if (Auth::user())
        <a href="{{route('article.create')}}" class="btn btn-success">
            Ajouter un article
        </a>
      @endif


      {{$articles->links()}}
    <div class="row">
        @foreach ($articles as $a)
            <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="card mb-4 shadow-sm">
                    <img
                        src="{{$a->img_url}}"
                        class="bd-placeholder-img card-img-top"
                    />
                    <div class="card-body">
                        <h5 class="card-title">{{ $a->titre }}</h5>
                        <a href="{{ route('article.show',$a->id) }}" class="btn btn-dark">
                            Lire l'article
                        </a>
                    </div>
                </div>
            </div>
      @endforeach
    </div>
    {{$articles->links()}}
  </div>
</div>


@endsection

blog/resources/views/pages/article/show.blade.php
@extends('layouts.public')
@section('content')
<div class="album py-5 bg-light">
    <div class="container">
        <h1>{{$article->titre}}</h1>
        <hr />
        {{$article->auteur->name}}
        {{$article->created_at}}

        @if($article->created_at != $article->updated_at)
        <i>Article modifié le ({{$article->updated_at}})</i>
        @endif

        @if($article->user_id == Auth::user()->id)
            <a href="{{route('article.edit', $article->id)}}">Modifier</a>
            <form
                id="delete-form"
                class="d-inline-block"
                action="{{route('article.destroy', $article->id)}}"
                method="POST"
            >
                @csrf
                @method('DELETE')
                <button type="submit" class="btn btn-link">Supprimer</button>

            </form>

        @endif

        <hr />
        <img src="{{$article->img_url}}" class="w-100"  />
        <div>
            @foreach ($article->parsed_body as $line)
                <p>{{$line}}</p>
            @endforeach
        </div>
    </div>
</div>



@endsection


@section('js')
<script>
    $('#delete-form').submit(function(e){
        e.preventDefault();
        if( confirm("Êtes vous sur de supprimer cet article")){
            e.currentTarget.submit();
        }
    });
</script>
@endsection

blog/resources/views/pages/catalog.blade.php
@extends('layouts.public')
@section('content')
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
          <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
          <div class="card-body">
             <h5 class="card-title">Card title</h5>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

blog/resources/views/pages/contact.blade.php
@extends('layouts.public')
@section('content')
<div class="container p-5">
  <form>
    <div class="form-group">
      <label for="exampleFormControlInput1">Email address</label>
      <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
    </div>
    <div class="form-group">
      <label for="exampleFormControlTextarea1">Example textarea</label>
      <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
    </div>
    <button type="submit" name="button" class="btn btn-success">Envoyer</button>
  </form>
</div>

@endsection

blog/resources/views/pages/index.blade.php
@extends('layouts.public')
@section('content')
  <section class="jumbotron text-center">
    <div class="container">
      <h1>Album example</h1>
      <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>
      <p>
        <a href="#" class="btn btn-primary my-2">Main call to action</a>
        <a href="#" class="btn btn-secondary my-2">Secondary action</a>
      </p>
    </div>
  </section>
  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
            <div class="card-body">
              <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                </div>
                <small class="text-muted">9 mins</small>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
@endsection